name: 'build wheels with manylinux2014_x86_64'
description: 'build wheels with manylinux2014_x86_64'
inputs:
    pyver:
        required: true
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.pyver }}
