version: 2
formats: all

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  apt_packages:
    - libgsl0-dev

python:
  version: 3
  install:
    - requirements: sphinx/requirements.txt
  system_packages: true


