name: flaremodel
channels:
  - conda-forge
dependencies:
  - numpy<1.20
  - scipy
  - matplotlib
  - setuptools
  - cython
  - conda-forge::gsl
  - conda-forge::compilers
  - conda-forge::llvm-openmp
