name: Build manylinux wheels, upload to PyPI upon release

on: push

jobs:
  build:
    name: Build manylinux wheels, upload to PyPI upon release
    runs-on: ubuntu-latest
    strategy:
        matrix:
            pyver: [3.7, 3.8, 3.9, "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Build manylinux wheel
        uses: ./.github/workflows/actions/build_manylinux
        with:
            pyver: ${{ matrix.pyver }}
      - uses: actions/upload-artifact@v2-preview
        with:
          name: flaremodel-wheel-manylinux
          path: wheelhouse/*manylinux*.whl
    
  upload:
    name: Upload wheels to test.pypi
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Check
        run : ls -l flaremodel-wheel-manylinux
        #if: github.event_name == 'release' && github.event.action == 'created'
      - name: Publish wheels to test.pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: flaremodel-wheel-manylinux

