name: Build flaremodel sdist

on: push

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Cython and numpy
        run : pip install cython "numpy<1.20"
      - name: Install GSL
        run : sudo apt-get install libgsl0-dev
      - name: Build sdist
        run : python setup.py sdist
      - name: Publish package to test.pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_TOKEN }}
